### ISSUE TITLE
Can't turn up past 100% on the Fedora OS volume sceeen.

### ISSUE THREAD

**Issue by Dunard** [stefansundin/powermate-linux#22]
It's only go to the line or dot on the 200% volume screen. Stop at 100%.

I'm using Fedora 38 Workstation.

**Comment by stefansundin** [comment]
Hello. It has been a while since I used this program now, but I think the way it works is: the max volume the program will set is normally 100%, but if the volume is already above 100% then the max is 150%.

This code seems to set the limit: https://github.com/stefansundin/powermate-linux/blob/a5aed4058e4139c9a316419a679c4aa494c51e07/main.c#L241-L248

It would make sense if this was an option in `powermate.toml` instead. But for the time being maybe you can change the logic in this code snippet and compile it yourself?

**Comment by Dunard** [comment]
Yeah it doesn't get it past 100. That is the same code from 3 years ago. Maybe it got broken from the later Fedora releases since then. I will try out the 2.50 to see what it does.
